### ISSUE TITLE
Large number of deprecation warnings when running npm install

### ISSUE THREAD

**Issue by jbteves** [niivue/niivue-ui#28]
Log below, following README instructions on MacOS 12.1 "Monterey" with a brew-installed npm.

```
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated html-webpack-plugin@3.2.0: 3.x is no longer supported
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated eslint-loader@2.2.1: This loader has been deprecated. Please use eslint-webpack-plugin
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
```

It also lists 74 vulnerabilities but since this is javascript I assume that's barely any at all, relatively speaking.

Unclear how much power y'all have to fix these since it doesn't tell me where these dependencies come from but I thought I'd at least record the problem.

**Comment by hanayik** [comment]
Hi Josh,

Don't do anything mission critical with the UI project right now. It's undergoing a major rewrite using vite as the build tool, and react as the front end framework. Those deprecation warning you see are due to using Vue cli which has had that issue historically. I've abandoned it in the rewrite of the UI.

Sorry if you wasted any time. I'll update the UI readme to reflect the status of the rewrite.
________________________________
From: Joshua Teves ***@***.***>
Sent: Wednesday, February 2, 2022 5:52:17 PM
To: niivue/niivue-ui ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [niivue/niivue-ui] Large number of deprecation warnings when running npm install (Issue #28)


Log below, following README instructions on MacOS 12.1 "Monterey" with a brew-installed npm.

npm WARN deprecated ***@***.***: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated ***@***.***: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated ***@***.***: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated ***@***.***: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated ***@***.***: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated ***@***.***: 3.x is no longer supported
npm WARN deprecated ***@***.***: this library is no longer supported
npm WARN deprecated ***@***.***: This loader has been deprecated. Please use eslint-webpack-plugin
npm WARN deprecated ***@***.***: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated @***@***.***: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @***@***.***: Moved to 'npm install @sideway/address'
npm WARN deprecated @***@***.***: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @***@***.***: Switch to 'npm install joi'
npm WARN deprecated @***@***.***: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated ***@***.***: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated ***@***.***: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated ***@***.***: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated ***@***.***: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.


It also lists 74 vulnerabilities but since this is javascript I assume that's barely any at all, relatively speaking.

Unclear how much power y'all have to fix these since it doesn't tell me where these dependencies come from but I thought I'd at least record the problem.

**Comment by jbteves** [comment]
I didn't waste any appreciable time, nor due anything critical. Probably good to note in the README if you're asking people to give UI feedback though!

**Comment by hanayik** [comment]
closing this issue now since it will be resolved when the react version of the ui is merged in soon
